### PR TITLE
Staging server vagrant

### PR DESCRIPTION
**Pull request by mirbitu**
Added staging server to Vagrantfile
Modified deployment server size on creation
Included HTTPS setup with nginx

### CODE REVIEW

**Comment by var-i** [comment]
Good job! I would just remove the repo cloning part and .env setup since we do it with ansible and we pull docker images instead of the whole repo

**Comment by var-i** [comment]
also, can we move this to the infrastructure folder?

**Comment by mirbitu** [comment]
> Good job! I would just remove the repo cloning part and .env setup since we do it with ansible and we pull docker images instead of the whole repo

I'm not sure if I'll be able to reach the desired files like that / how I'd do it

**Comment by mirbitu** [comment]
> also, can we move this to the infrastructure folder?

might need to do some pathing changes if we do

**Review by var-i — APPROVED** [review]

**Review by var-i — APPROVED** [review]

**Pull request merged**
